name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Release ]
        compiler: [ g++, clang++ ]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      COMPILER: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Configure ccache
      uses: hendrikmuhs/ccache-action@v1
      
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y clang libgtest-dev libgoogle-glog-dev libeigen3-dev \
          libboost-dev libfmt-dev
    
    - name: Install OpenCV 4.4
      run: |
        wget https://github.com/opencv/opencv/archive/4.4.0.zip -P ${{github.workspace}} -q
        unzip -q ${{github.workspace}}/4.4.0.zip -d ${{github.workspace}} && rm ${{github.workspace}}/4.4.0.zip
        cd ${{github.workspace}}/opencv-4.4.0 && mkdir build && cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DBUILD_opencv_dnn=OFF -DBUILD_opencv_java_bindings_gen=OFF \
          -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF
        cmake --build . -j2
        sudo make install
          
    - name: Install Ceres
      run: |
        git clone https://github.com/ceres-solver/ceres-solver.git ${{github.workspace}}/ceres-solver
        cd ${{github.workspace}}/ceres-solver && mkdir build && cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARKS=OFF
        cmake --build . -j2
        sudo make install
          
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_CXX_COMPILER=/usr/bin/${{env.COMPILER}} \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C -V ${{env.BUILD_TYPE}}
      
